neo4j:
  image: neo4j
  environment:
    NEO4JLABS_PLUGINS: '["apoc", "n10s"]'
    NEO4J_AUTH: none
    NEO4J_apoc_export_file_enabled: "true"
    NEO4J_apoc_import_file_enabled: "true"
    NEO4J_apoc_import_file_use__neo4j__config: "true"
  volumes:
    - ./td_data:/var/lib/neo4j/import/td_data
  privileged: "true"
  ports:
    - "7474:7474"
    - "7687:7687"