bsbm-virtuoso-benchmark:
  image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
  environment:
    SPARQL_UPDATE: "true"
    DBA_PASSWORD: "dba"
    DEFAULT_GRAPH: "http://bsbm/"
    VIRT_TransactionAfterImageLimit: "150000000"
    VIRT_MaxQueryExecutionTime: "600"
    VIRT_MaxQueryCostEstimationTime: "1200"
    VIRT_SQL_QUERY_TIMEOUT: "600"
  volumes:
    - ./db/toLoad:/data/toLoad
  privileged: true
  ports:
    - "8890:8890"
    - "1111:1111"